import pool from '../db/pool.js';

// Helper function to create notifications
const createNotification = async (userId, message, type = 'info', relatedId = null) => {
  try {
    await pool.query(
      `INSERT INTO notifications (user_id, message, type, related_id)
       VALUES ($1, $2, $3, $4)`,
      [userId, message, type, relatedId]
    );
  } catch (error) {
    console.error('Failed to create notification:', error);
  }
};

export const getAllReports = async (req, res) => {
  try {
    const result = await pool.query(
      'SELECT * FROM reports ORDER BY date_generated DESC'
    );
    res.json(result.rows);
  } catch (error) {
    console.error('Get reports error:', error);
    res.status(500).json({ error: 'Failed to fetch reports' });
  }
};

export const getReportById = async (req, res) => {
  try {
    const { id } = req.params;
    const result = await pool.query(
      'SELECT * FROM reports WHERE id = $1',
      [id]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'Report not found' });
    }

    res.json(result.rows[0]);
  } catch (error) {
    console.error('Get report error:', error);
    res.status(500).json({ error: 'Failed to fetch report' });
  }
};

export const createReport = async (req, res) => {
  try {
    const { title, description, type, generated_by_id, generated_by_name, directed_to_id, directed_to_name, data, status } = req.body;

    if (!title || !type) {
      return res.status(400).json({ error: 'Title and type are required' });
    }

    if (!generated_by_id || !generated_by_name) {
      return res.status(400).json({ error: 'Generated by user info is required' });
    }

    const result = await pool.query(
      `INSERT INTO reports (title, description, type, generated_by_id, generated_by_name, directed_to_id, directed_to_name, data, status)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
       RETURNING *`,
      [title, description, type, generated_by_id, generated_by_name, directed_to_id, directed_to_name, JSON.stringify(data) || null, status || 'draft']
    );

    const newReport = result.rows[0];

    // Send notification to admins about new report
    try {
      const admins = await pool.query(
        'SELECT id FROM users WHERE role = $1',
        ['admin']
      );

      for (const admin of admins.rows) {
        await createNotification(
          admin.id,
          `New report "${title}" has been created by ${generated_by_name}`,
          'report_created',
          newReport.id
        );
      }

      // Send notification to directed_to person if specified
      if (directed_to_id) {
        await createNotification(
          directed_to_id,
          `Report "${title}" has been directed to you by ${generated_by_name}`,
          'report_directed',
          newReport.id
        );
      }
    } catch (error) {
      console.error('Failed to notify about report:', error);
    }

    res.status(201).json(newReport);
  } catch (error) {
    console.error('Create report error:', error);
    res.status(500).json({ error: error.message || 'Failed to create report' });
  }
};

export const updateReport = async (req, res) => {
  try {
    const { id } = req.params;
    const { title, description, type, status, data, directed_to_id, directed_to_name } = req.body;

    const result = await pool.query(
      `UPDATE reports SET 
       title = COALESCE($2, title),
       description = COALESCE($3, description),
       type = COALESCE($4, type),
       status = COALESCE($5, status),
       data = COALESCE($6, data),
       directed_to_id = COALESCE($7, directed_to_id),
       directed_to_name = COALESCE($8, directed_to_name),
       updated_at = CURRENT_TIMESTAMP
       WHERE id = $1
       RETURNING *`,
      [id, title, description, type, status, data ? JSON.stringify(data) : null, directed_to_id, directed_to_name]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'Report not found' });
    }

    res.json(result.rows[0]);
  } catch (error) {
    console.error('Update report error:', error);
    res.status(500).json({ error: 'Failed to update report' });
  }
};

export const deleteReport = async (req, res) => {
  try {
    const { id } = req.params;

    const result = await pool.query(
      'DELETE FROM reports WHERE id = $1 RETURNING *',
      [id]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'Report not found' });
    }

    res.json({ message: 'Report deleted successfully' });
  } catch (error) {
    console.error('Delete report error:', error);
    res.status(500).json({ error: 'Failed to delete report' });
  }
};

export const publishReport = async (req, res) => {
  try {
    const { id } = req.params;

    const result = await pool.query(
      'UPDATE reports SET status = $1, updated_at = CURRENT_TIMESTAMP WHERE id = $2 RETURNING *',
      ['published', id]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'Report not found' });
    }

    res.json(result.rows[0]);
  } catch (error) {
    console.error('Publish report error:', error);
    res.status(500).json({ error: 'Failed to publish report' });
  }
};
